### ISSUE TITLE
Online assembler reads only last 4 bytes of immediate

### ISSUE THREAD

**Issue by fbarbari** [defuse/defuse.ca#28]
Hello, I don't know if this is the right place for issues with the online assembler and disassembler.

When I try to assemble `mov eax, 0x0123456789abcdef`, it doesn't give any error and outputs this:
```
Assembly
Raw Hex (zero bytes in bold):

B8EFCDAB89   

String Literal:

"\xB8\xEF\xCD\xAB\x89"

Array Literal:

{ 0xB8, 0xEF, 0xCD, 0xAB, 0x89 }

Disassembly:
0:  b8 ef cd ab 89          mov    eax,0x89abcdef
```

It seems to me that only the last 4 bytes of the immediate are read while the rest is ignored.

**Comment by defuse** [comment]
`mov eax, 0x0123456789abcdef` would not be a valid instruction since EAX is only 32 bits. My assembler just shells out to gcc/as, so I guess they chose to handle that case by taking the least-significant 32 bits of the constant. I agree that it would be better to produce an error, but that's what gcc does. In any case, thanks for the report!
